//! Crate-level integration tests for `keysynth::extract::t60`.
//!
//! Per the issue #3 P3 contract: golden test against
//! `bench-out/REF/sfz_salamander_grand_v3_C4.wav` (committed on main at
//! `0fb3840`).

use std::path::Path;

use keysynth::extract::decompose::Partial;
use keysynth::extract::t60::extract_t60;

const REF_WAV: &str = "bench-out/REF/sfz_salamander_grand_v3_C4.wav";

/// Pinned `extract_t60` outputs on
/// `bench-out/REF/sfz_salamander_grand_v3_C4.wav` (5 s SFZ Salamander
/// Grand Piano V3 C4 render, sha256 38985a1…163fc1). Generated by
/// `cargo run --bin extract_dump -- bench-out/REF/sfz_salamander_grand_v3_C4.wav 261.63`
/// and re-pinned whenever the algorithm changes.
///
/// Cross-reference: the existing `analyse` binary reports
///   h1=18.14, h2=11.21, h3=9.58, h4=7.38, h5=6.98, h6=7.93, h7=8.98, h8=8.66
/// for the same WAV. This extractor agrees on h3/h4/h7 (the cleanest
/// partials) within ~1 %; it disagrees on h1/h2/h5/h6/h8 because of:
/// - h1: T60 ≈ 18 s implies only ~10 dB drop over the 5 s render, so the
///   algorithm's -45 dB threshold never fires AND the R² gate trips on
///   amplitude beating between detuned neighbour strings in the SFZ
///   multi-mic recording. Result: -1 sentinel.
/// - h2, h5, h6, h8: different bin window (±10 cents vs analyse's
///   harmonic-track) + different regression segment cause genuine
///   algorithm disagreement, locked in here as the pinned baseline.
///
/// Tuple: (partial_n, freq_hz, expected_t60_sec). `expected_t60_sec` of
/// `-1.0` means the algorithm should return the no-decay sentinel (and
/// the test treats that as a pass for that partial).
const EXTRACT_T60_GOLDEN: [(usize, f32, f32); 8] = [
    (1, 261.6, -1.0), // sentinel: no usable decay over 5 s
    (2, 523.1, 2.09),
    (3, 784.7, 9.59),  // strict: matches analyse within 1 %
    (4, 1046.2, 7.38), // strict: matches analyse within 1 %
    (5, 1307.8, 3.01),
    (6, 1569.3, 8.51),
    (7, 1830.9, 8.96), // strict: matches analyse within 1 %
    (8, 2092.5, 7.21),
];

fn read_wav_mono_f32(path: &Path) -> Option<(Vec<f32>, f32)> {
    let mut reader = hound::WavReader::open(path).ok()?;
    let spec = reader.spec();
    let channels = spec.channels as usize;
    let sr = spec.sample_rate as f32;

    let samples: Vec<f32> = match spec.sample_format {
        hound::SampleFormat::Float => reader.samples::<f32>().filter_map(|s| s.ok()).collect(),
        hound::SampleFormat::Int => {
            let max = (1i64 << (spec.bits_per_sample - 1)) as f32;
            reader
                .samples::<i32>()
                .filter_map(|s| s.ok())
                .map(|s| s as f32 / max)
                .collect()
        }
    };

    let mono: Vec<f32> = if channels <= 1 {
        samples
    } else {
        samples
            .chunks(channels)
            .map(|c| c.iter().copied().sum::<f32>() / channels as f32)
            .collect()
    };
    Some((mono, sr))
}

#[test]
fn golden_sfz_c4_per_partial_t60() {
    let path = Path::new(REF_WAV);
    let Some((signal, sr)) = read_wav_mono_f32(path) else {
        panic!("failed to read {REF_WAV}");
    };

    let partials: Vec<Partial> = EXTRACT_T60_GOLDEN
        .iter()
        .map(|&(n, f, _)| Partial {
            n,
            freq_hz: f,
            init_db: 0.0,
        })
        .collect();

    let out = extract_t60(&signal, sr, &partials);
    assert_eq!(
        out.seconds.len(),
        partials.len(),
        "T60Vector length mismatch"
    );

    // Tolerance: ±15 % around each pinned positive value, sentinel must
    // remain sentinel. Pinned values represent THIS extractor's behaviour
    // on the committed SFZ ref WAV — the test catches regressions in the
    // algorithm itself, not disagreement with the `analyse` binary
    // (cross-extractor disagreement is documented in EXTRACT_T60_GOLDEN).
    for (i, &got) in out.seconds.iter().enumerate() {
        let (n, _, expected) = EXTRACT_T60_GOLDEN[i];
        if expected < 0.0 {
            assert!(
                got < 0.0,
                "partial n={n}: expected sentinel, got positive T60 {got:.3} s",
            );
        } else {
            assert!(
                got > 0.0,
                "partial n={n}: expected positive T60 ~{expected:.3} s, got sentinel",
            );
            let lo = expected * 0.85;
            let hi = expected * 1.15;
            assert!(
                got >= lo && got <= hi,
                "partial n={n}: T60 {got:.3} s outside ±15 % of pinned \
                 {expected:.3} s [{lo:.3}, {hi:.3}]",
            );
        }
    }
}
