//! CLI smoke for the `score` library: a WAV vs itself should sit well
//! below the calibration band on every component, so the weighted total
//! must be small. Acts as a regression anchor for both the loss code and
//! the default weight set.

use std::path::PathBuf;

use keysynth::score::{loss_paths, LossWeights};
use keysynth::synth::midi_to_freq;

#[test]
fn ref_vs_self_total_is_small() {
    let mut path = PathBuf::from("bench-out/REF");
    path.push("sfz_salamander_grand_v3_C4.wav");
    if !path.exists() {
        // Reference WAV not committed in this checkout — skip rather
        // than fail. The bench-out/REF directory is generated by the
        // bench harness and may or may not be present in CI.
        eprintln!("score_basic: skipping (no {})", path.display());
        return;
    }

    let f0 = midi_to_freq(60);
    let weights = LossWeights::default();
    let breakdown =
        loss_paths(&path, &path, f0, &weights).expect("loss_paths should succeed for self-pair");
    assert!(
        breakdown.total < 5.0,
        "self-loss should be small, got total={} ({:?})",
        breakdown.total,
        breakdown
    );
}
