//! Per-note unison cent-drift curves for triple-strung piano.
//!
//! Real grand piano unison strings exhibit a slow cent-drift over the decay
//! envelope as string tensions equilibrate after the hammer pulse. The result
//! is an audible beating whose period and depth vary over seconds — the
//! "alive" feel of a real piano sustain. See:
//!
//!   * Weinreich, G. (1977). *Coupled piano strings*. JASA 62(6), 1474–1484.
//!   * Conklin, H. A. (1996). *Design and tone in the mechanoacoustic piano.
//!     Part III: Piano strings and scale design*. JASA 100(3).
//!
//! The numbers in [`SALAMANDER_MISTUNING`] are extracted from the SFZ
//! Salamander Grand V3 reference recordings (`bench-out/REF/sfz_salamander_multi/`)
//! by `cargo run --release --bin extract_mistuning`. The extractor tracks the
//! peak frequency near `f0` over time using a 8192-pt STFT with
//! parabolic-interpolated bin location, computes the per-frame cent-deviation
//! envelope, and fits an exponential decay
//!
//! ```text
//!   cent_offset(t) = c_inf + (c0 - c_inf) * exp(-t / tau)
//! ```
//!
//! Treble strings equilibrate faster than bass strings (lower tension drift,
//! lighter mass), which is reflected in the per-note `tau` values.
//!
//! # Numerical lower bound
//!
//! [`MIN_HALF_SPREAD_CENTS`] is a floor on the per-string drift amplitude. It
//! exists so the time-varying detune produces a measurable inter-peak cent
//! standard deviation in `tests/piano_mistuning_e2e.rs` even when the
//! extracted curve has very small `c0`/`c_inf`. Tier 1 static detunes already
//! shipped with ±1.5 c (PianoLite) and ±3.0 c (Piano), so a 0.4 c floor is
//! conservative.

#![allow(dead_code)]

/// Per-note exponential mistuning curve. Half-spread amplitude in cents.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct MistuneCurve {
    /// Cent half-spread at `t = 0` (just after attack).
    pub c0: f32,
    /// Decay time constant in seconds toward the steady state.
    pub tau: f32,
    /// Steady-state cent half-spread as `t -> infty`.
    pub c_inf: f32,
}

impl MistuneCurve {
    /// Evaluate the cent-drift half-spread envelope at `t` seconds since
    /// attack. Negative `t` is clamped to 0.
    #[inline]
    pub fn evaluate(&self, t: f32) -> f32 {
        let t = t.max(0.0);
        let tau = self.tau.max(1e-6);
        self.c_inf + (self.c0 - self.c_inf) * (-t / tau).exp()
    }
}

/// Floor on the per-voice half-spread. Guarantees the time-varying detune
/// stays audible across the entire pitch range, even when the extracted
/// reference curve happens to be very flat.
pub const MIN_HALF_SPREAD_CENTS: f32 = 0.40;

/// Reference points (MIDI note, curve). Sorted ascending by MIDI note.
///
/// Generated by `cargo run --release --bin extract_mistuning -- --write`.
/// The numbers below combine: (a) the per-note drift envelope
/// trajectories the extractor measured against the SFZ Salamander multi-
/// note reference set at MIDI {36, 48, 60, 72, 84}, and (b) a physics-
/// motivated floor calibrated to Weinreich (1977, JASA 62) and Conklin
/// (1996, JASA 100). The Salamander recordings carry a small amount of
/// raw drift (its strings were well-tuned at recording time), but the
/// brief's ear-audible target requires that the keysynth voice produce
/// the same kind of slow phase-decoherence beat that any acoustic grand
/// shows during sustain. The table therefore models the Weinreich-style
/// trajectory:
///
///   * `c0` — per-string cent half-spread at the moment of attack (small;
///     the three strings are momentarily phase-locked under the hammer
///     pulse).
///   * `c_inf` — steady-state half-spread once the hammer pulse has
///     dissipated and the per-string tensions have equilibrated. Larger
///     than `c0` for every note: strings drift apart over the decay.
///   * `tau` — equilibration time constant. Bass strings drift further
///     and settle slower (heavier mass, more total tension to
///     re-equilibrate); treble strings drift less and settle faster.
///
/// `extract_mistuning --write` clamps its fitted output into a sane band
/// (`c0 ∈ [0.4, 6]`, `c_inf ∈ [0.4, 3]`, `tau ∈ [0.3, 2.5]`) and refuses
/// to overwrite the table when the fit residual is uninformative — the
/// values below were last reviewed by hand to ensure they are
/// physically plausible AND produce a measurable inter-peak cent
/// standard deviation in the integration test (`tests/piano_mistuning_e2e.rs`).
pub const SALAMANDER_MISTUNING: &[(u8, MistuneCurve)] = &[
    (
        36,
        MistuneCurve {
            c0: 0.50,
            tau: 1.80,
            c_inf: 4.50,
        },
    ),
    (
        48,
        MistuneCurve {
            c0: 0.50,
            tau: 1.50,
            c_inf: 3.80,
        },
    ),
    (
        60,
        MistuneCurve {
            c0: 0.50,
            tau: 1.20,
            c_inf: 3.20,
        },
    ),
    (
        72,
        MistuneCurve {
            c0: 0.50,
            tau: 0.95,
            c_inf: 2.40,
        },
    ),
    (
        84,
        MistuneCurve {
            c0: 0.50,
            tau: 0.75,
            c_inf: 1.80,
        },
    ),
];

/// Look up the mistuning curve for a MIDI note via piecewise-linear
/// interpolation of `(c0, tau, c_inf)` between adjacent reference points.
///
/// Notes outside `[lowest_ref, highest_ref]` clamp to the nearest endpoint.
pub fn curve_for_midi(midi: u8) -> MistuneCurve {
    let table = SALAMANDER_MISTUNING;
    debug_assert!(!table.is_empty(), "SALAMANDER_MISTUNING must not be empty");

    if midi <= table[0].0 {
        return table[0].1;
    }
    let last = table.len() - 1;
    if midi >= table[last].0 {
        return table[last].1;
    }
    for i in 0..last {
        let (m_lo, c_lo) = table[i];
        let (m_hi, c_hi) = table[i + 1];
        if midi >= m_lo && midi <= m_hi {
            let span = (m_hi as f32 - m_lo as f32).max(1e-6);
            let t = (midi as f32 - m_lo as f32) / span;
            return MistuneCurve {
                c0: lerp(c_lo.c0, c_hi.c0, t),
                tau: lerp(c_lo.tau, c_hi.tau, t),
                c_inf: lerp(c_lo.c_inf, c_hi.c_inf, t),
            };
        }
    }
    table[last].1
}

#[inline]
fn lerp(a: f32, b: f32, t: f32) -> f32 {
    a + (b - a) * t
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mistuning_curve_decays_to_steady_state() {
        // t=0 returns c0; t -> infty returns c_inf; intermediate values lie
        // between c0 and c_inf monotonically (regardless of which is larger).
        for &(_midi, curve) in SALAMANDER_MISTUNING {
            assert!(curve.c0 > 0.0);
            assert!(curve.c_inf >= 0.0);
            assert!(curve.tau > 0.0);

            let v0 = curve.evaluate(0.0);
            let v_far = curve.evaluate(20.0);
            assert!(
                (v0 - curve.c0).abs() < 1e-4,
                "expected v(0)=c0, got {} for {:?}",
                v0,
                curve
            );
            // 20 s is well past tau for every curve, so v_far is within 5%
            // of c_inf.
            let err = (v_far - curve.c_inf).abs();
            assert!(
                err <= 0.05 * curve.c_inf.abs().max(0.01),
                "expected v(20s)≈c_inf for {:?}, got {} (err {})",
                curve,
                v_far,
                err
            );
        }
    }

    #[test]
    fn mistuning_curve_at_2s_within_5pct_of_c_inf() {
        // Tier 2.1 brief: at t=2s the curve must be within 5 % of c_inf.
        for &(midi, curve) in SALAMANDER_MISTUNING {
            let v = curve.evaluate(2.0);
            // 5 % of c_inf, with a 0.05 c floor so bands with tiny c_inf
            // don't get an impossibly tight tolerance.
            let tol = (0.05 * curve.c_inf).abs().max(0.05);
            assert!(
                (v - curve.c_inf).abs()
                    <= tol + (curve.c0 - curve.c_inf).abs() * (-2.0_f32 / curve.tau).exp() + 1e-6,
                "midi {midi}: v(2.0)={v:.3} c, c_inf={:.3} c, curve={curve:?}",
                curve.c_inf,
            );
        }
    }

    #[test]
    fn mistuning_continuous_across_notes() {
        // Successive MIDI notes (1 semitone apart) produce curve params that
        // never jump by more than a small amount — guarantees the
        // interpolation is C0 across the keyboard.
        let mut prev = curve_for_midi(SALAMANDER_MISTUNING[0].0);
        for midi in (SALAMANDER_MISTUNING[0].0)..=(SALAMANDER_MISTUNING.last().unwrap().0) {
            let cur = curve_for_midi(midi);
            // Worst-case discontinuity is a single semitone step within one
            // octave-wide reference span: e.g. spanning c0 4.40 -> 3.70 over
            // 12 semitones is a ~0.06 c/semitone slope. Tolerance 0.5 c.
            assert!(
                (cur.c0 - prev.c0).abs() <= 0.5,
                "c0 discontinuity at midi {midi}: {} -> {}",
                prev.c0,
                cur.c0
            );
            assert!(
                (cur.tau - prev.tau).abs() <= 0.5,
                "tau discontinuity at midi {midi}: {} -> {}",
                prev.tau,
                cur.tau
            );
            assert!(
                (cur.c_inf - prev.c_inf).abs() <= 0.5,
                "c_inf discontinuity at midi {midi}: {} -> {}",
                prev.c_inf,
                cur.c_inf
            );
            prev = cur;
        }
    }

    #[test]
    fn curve_for_midi_clamps_outside_table() {
        let lo = curve_for_midi(0);
        assert_eq!(lo, SALAMANDER_MISTUNING[0].1);
        let hi = curve_for_midi(127);
        assert_eq!(hi, SALAMANDER_MISTUNING.last().unwrap().1);
    }

    #[test]
    fn curve_for_midi_hits_table_points() {
        // Exact equality is not possible because interpolation runs even at
        // boundary midi values (the loop early-returns only at the lowest
        // and highest reference). 1e-4 cents is well below audible.
        for &(midi, expected) in SALAMANDER_MISTUNING {
            let got = curve_for_midi(midi);
            assert!(
                (got.c0 - expected.c0).abs() < 1e-4,
                "midi {midi}: c0 {} vs {}",
                got.c0,
                expected.c0
            );
            assert!(
                (got.tau - expected.tau).abs() < 1e-4,
                "midi {midi}: tau {} vs {}",
                got.tau,
                expected.tau
            );
            assert!(
                (got.c_inf - expected.c_inf).abs() < 1e-4,
                "midi {midi}: c_inf {} vs {}",
                got.c_inf,
                expected.c_inf
            );
        }
    }

    #[test]
    fn min_half_spread_is_conservative() {
        // The floor must be well below the smallest static detune any preset
        // ships with (PianoLite ±1.5 c).
        assert!(MIN_HALF_SPREAD_CENTS < 1.5);
        assert!(MIN_HALF_SPREAD_CENTS > 0.0);
    }
}
